include:
  - project: devops/ci-config
    file:
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/audit-jobs.gitlab-ci.yml

stages:
  - build
  - test
  - accessibility
  - release
  - deploy

variables:
  # using build_tag var from container-flexible template
  release_tag: $CI_REGISTRY_IMAGE/$CI_ENVIRONMENT_SLUG:latest

bundler-audit:
  allow_failure: false

#
# Environments
#

.development:
  environment:
    name: development
    url: https://archives-dev.lib.duke.edu
  tags:
    - development
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $DEVELOPMENT_REF_NAME

.staging:
  environment:
    name: staging
    url: https://archives-test.lib.duke.edu
  tags:
    - staging
  only:
    variables:
      - $CI_COMMIT_REF_NAME == $STAGING_REF_NAME

.production:
  environment:
    name: production
    url: https://archives.lib.duke.edu
  tags:
    - production
  only:
    - main

#
# Jobs
#

build:
  extends: .build

#
# Test jobs
#

test:
  extends: .test
  script:
    - docker pull $build_tag
    - make clean test

rubocop:
  extends: .test
  script:
    - docker pull $build_tag
    - make rubocop
  allow_failure: true

#
# Accessibility is in a separate stage to not
# conflict with default test suite.
#

accessibility:
  extends: .job
  stage: accessibility
  script:
    - docker pull $build_tag
    - make clean accessibility
  allow_failure: true

#
# Release jobs
#

release_development:
  extends:
    - .release
    - .development

release_staging:
  extends:
    - .release
    - .staging

release_production:
  extends:
    - .release
    - .production

#
# Deploy jobs
#

.deploy:
  extends: .job
  stage: deploy
  script:
    - docker pull $release_tag
    - sudo -n systemctl reload-or-restart docker-stack@dul-arclight

deploy_development:
  extends:
    - .deploy
    - .development

deploy_staging:
  extends:
    - .deploy
    - .staging

deploy_production:
  extends:
    - .deploy
    - .production
  when: manual
