# Configurable custom sitemaps, esp. for aggregators to harvest collections
# matching a particular query.

# Note that other query parameters for this feature are hard-coded in
# custom_sitemaps_controller.rb. E.g., only collection pages are
# included, and items listed are sorted by last indexed date (new to old).

# You may specify multiple query parameters, one per line, e.g.:

# test_ua_bw_photos:
#  query: |
#    formats_ssim:"Black-and-white photographs"
#    repository_sim:"Duke University Archives"

# List HOM collections for NLM History of Medicine Finding Aids Consortium
nlm_history_of_medicine:
  query: |
    names_ssim:"History of Medicine Collections (Duke University)"

# List only Rubenstein & UA finding aids, exclude other "repositories"
rubenstein_ua:
  query: |
    repository_ssm:("David M. Rubenstein Rare Book & Manuscript Library" OR "Duke University Archives")
