version: '3.7'

services:
  selenium:
    # This image is a multi-arch alternative to:
    # https://hub.docker.com/r/selenium/standalone-chrome/
    image: seleniarm/standalone-chromium
    ports:
      - 4444:4444
    volumes:
      - /dev/shm:/dev/shm
    environment:
      # https://stackoverflow.com/a/63310469
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
      # https://github.com/SeleniumHQ/docker-selenium/issues/429
      - START_XVFB=false
    container_name: selenium

  app:
    container_name: testapp
    volumes:
      - ../spec/fixtures:/data:ro
    environment:
      - RAILS_ENV=test
      - FINDING_AID_DATA=spec/fixtures
    ports:
      - '3002:3002'
    depends_on:
      - selenium
